name: x_ride_user
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.1.0
  easy_localization: ^3.0.7
  timezone: ^0.10.0
  flutter_native_splash: ^2.4.4
  overlay_support: ^2.1.0
  go_router: ^14.8.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  logger: ^2.5.0
  provider: ^6.1.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  gap: ^3.0.1
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  custom_rating_bar: ^3.0.0
  collection: ^1.19.1
  timeago: ^3.7.0
  hl_image_picker: ^1.2.16
  web_socket_client: ^0.1.5
  photo_view: ^0.15.0
  modal_bottom_sheet: ^3.0.0
  url_launcher: ^6.3.1
  flutter_spinkit: ^5.2.1
  random_avatar: ^0.0.8
  webview_flutter: ^4.10.0
  flutter_platform_alert: ^0.6.1
  pinch_zoom: ^2.0.0
  phone_numbers_parser: ^9.0.3
  pinput: ^5.0.1
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  flutter_map: ^8.0.0
  flutter_map_location_marker: ^9.1.1
  sliding_up_panel: ^2.0.0+1
  sensors_plus: ^6.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_tts: ^4.2.2
  timeline_tile_plus: ^0.0.3
  share_plus: ^10.1.4
  flutter_native_contact_picker: ^0.0.10




dependency_overrides: 
  flutter_map: ^7.0.2
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.3



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/jpg/
    - assets/json/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800